apiVersion: v1
kind: Service
metadata:
  name: airbyte-db-svc
spec:
  type: NodePort
  ports:
    - port: 5432
      protocol: TCP
  selector:
    airbyte: db
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: airbyte-db
spec:
  replicas: 1
  selector:
    matchLabels:
      airbyte: db
  template:
    metadata:
      labels:
        airbyte: db
    spec:
      containers:
        - name: airbyte-db-container
          image: airbyte/db:0.6.2-alpha
          resources:
            limits:
              memory: "256Mi"
              cpu: "500m"
          env:
            - name: POSTGRES_DB
              value: db-airbyte
            - name: POSTGRES_PASSWORD
              value: docker
            - name: POSTGRES_USER
              value: docker
          ports:
            - containerPort: 5432
      volumes:
        - name: airbyte-volume-db
          hostPath:
            path: /var/lib/postgresql/data
