apiVersion: apps/v1
kind: Deployment
metadata:
  name: init
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: init
  strategy:
    type: Recreate
  template:
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - ./scripts/create_mount_directories.sh /local_parent /tmp /tmp/airbyte_local
        env:
        - name: HACK_LOCAL_ROOT_PARENT
          value: /tmp
        - name: LOCAL_ROOT
          value: /tmp/airbyte_local
        image: airbyte/init:0.6.2-alpha
        imagePullPolicy: ""
        name: init
        resources: {}
        volumeMounts:
        - mountPath: /local_parent
          name: init-claim0
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: init-claim0
        persistentVolumeClaim:
          claimName: init-claim0
