apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f kube/docker-compose-resolved.yaml -o kube/local
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: scheduler
  name: scheduler
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: scheduler
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: scheduler
    spec:
      containers:
      - env:
        - name: AIRBYTE_VERSION
          value: 0.6.2-alpha
        - name: CONFIG_ROOT
          value: /data
        - name: DATABASE_PASSWORD
          value: docker
        - name: DATABASE_URL
          value: jdbc:postgresql://db:5432/airbyte
        - name: DATABASE_USER
          value: docker
        - name: LOCAL_DOCKER_MOUNT
          value: /tmp/airbyte_local
        - name: TRACKING_STRATEGY
          value: segment
        - name: WAIT_BEFORE_HOSTS
          value: "5"
        - name: WAIT_HOSTS
          value: db:5432
        - name: WAIT_HOSTS_TIMEOUT
          value: "45"
        - name: WORKSPACE_DOCKER_MOUNT
          value: workspace
        - name: WORKSPACE_ROOT
          value: /tmp/workspace
        image: airbyte/scheduler:0.6.2-alpha
        imagePullPolicy: ""
        name: airbyte-scheduler
        resources: {}
        volumeMounts:
        - mountPath: /var/run/docker.sock
          name: scheduler-claim0
        - mountPath: /tmp/workspace
          name: workspace
        - mountPath: /tmp/airbyte_local
          name: scheduler-claim2
        - mountPath: /data
          name: data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: scheduler-claim0
        persistentVolumeClaim:
          claimName: scheduler-claim0
      - name: workspace
        persistentVolumeClaim:
          claimName: workspace
      - name: scheduler-claim2
        persistentVolumeClaim:
          claimName: scheduler-claim2
      - name: data
        persistentVolumeClaim:
          claimName: data
