apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    io.kompose.service: seed
  name: seed
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: seed
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        io.kompose.service: seed
    spec:
      containers:
      - image: airbyte/seed:0.6.2-alpha
        imagePullPolicy: ""
        name: airbyte-data-seed
        resources: {}
        volumeMounts:
        - mountPath: /app/seed
          name: data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: data
        persistentVolumeClaim:
          claimName: data
