apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f kube/docker-compose-resolved.yaml -o kube/local
    kompose.version: 1.21.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: server
  name: server
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: server
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f kube/docker-compose-resolved.yaml -o kube/local
        kompose.version: 1.21.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: server
    spec:
      containers:
      - env:
        - name: AIRBYTE_VERSION
          value: 0.6.2-alpha
        - name: CONFIG_ROOT
          value: /data
        - name: DATABASE_PASSWORD
          value: docker
        - name: DATABASE_URL
          value: jdbc:postgresql://db:5432/airbyte
        - name: DATABASE_USER
          value: docker
        - name: TRACKING_STRATEGY
          value: segment
        - name: WAIT_BEFORE_HOSTS
          value: "5"
        - name: WAIT_HOSTS
          value: db:5432
        - name: WAIT_HOSTS_TIMEOUT
          value: "45"
        image: airbyte/server:0.6.2-alpha
        imagePullPolicy: ""
        name: airbyte-server
        ports:
        - containerPort: 8001
        resources: {}
        volumeMounts:
        - mountPath: /tmp/workspace
          name: workspace
        - mountPath: /data
          name: data
      restartPolicy: Always
      serviceAccountName: ""
      volumes:
      - name: workspace
        persistentVolumeClaim:
          claimName: workspace
      - name: data
        persistentVolumeClaim:
          claimName: data
status: {}
