apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airbyte-volume-workspace
  labels:
    airbyte: volume-local
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
