apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: airbyte-volume-data
  labels:
    airbyte: volume-data
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 500Mi
